version: '3.9'

services:
 
 #Node API service
 api:
  build: .
  ports:
   - 3000:3000
  volumes: 
   - .:/usr/src/app
   - /usr/src/app/node_modules
  environment:
   NODE_ENV: development
   PORT: 3000
   DATABASE: mongodb+srv://dolaptruongvu5:<password>@cluster0.kerqhao.mongodb.net/natours?retryWrites=true&w=majority
   DATABASE_LOCAL: mongodb://host.docker.internal:27017/natours-test
   DATABASE_PASSWORD: Va7O1g95Gn8HIE6E

   JWT_SECRET: my-supreme-secret
   JWT_EXPIRES_IN: 90d
   JWT_EMAILSECRET:  my-email-secret
   JWT_EMAILSECRET_EXPIRES_IN: 1d
   JWT_COOKIE_EXPIRES_IN: 90

   EMAIL_USERNAME: 251d9942380618
   EMAIL_PASSWORD: 11471717525ba4
   EMAIL_HOST: sandbox.smtp.mailtrap.io
   EMAIL_PORT: 25

   EMAIL_FROM :  dolaptruongvuzzz@gmail.com

   SENDGMAIL_USER :  tournatour226@gmail.com
   SENDGMAIL_PASSWORD: odybhrtyfkcyqbur

   STRIPE_SECRET_KEY: sk_test_51NefRuDno7xMeKTrzMCnv9bPLG16admqwuzEIxoxIO4i3vzka387oTnaNE8Vndg8E0lojE7zykLE71yFXFi4PqpU00MLlEDkEW
   STRIPE_PUBLIC_KEY: pk_test_51NefRuDno7xMeKTrHJyJParnyCentn0t6dmiX4hONCG3ZVjFrKtjZPBFNwMan8j6iNB2KEJs5w6U50miLAkyGIaX00WHltJnL3
  